- hosts: localhost
  become: true
  vars:
    oh_my_zsh_repo: https://github.com/robbyrussell/oh-my-zsh
    oh_my_zsh_users:
      - "root"
    oh_my_zsh_backup_zshrc: yes
  #vars_files: group_vars/ssmtp/variables.yml
  tasks:
    # - include: tasks/get_vars.yml
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/ohmyzsh.yml
    - include: tasks/mail_relay.yml
    - include: tasks/sshd_config.yml
