- hosts: localhost
  become: true
  vars:
    oh_my_zsh_repo: https://github.com/robbyrussell/oh-my-zsh

  handlers:
    - include: handlers/handler.yml

  tasks:
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/users.yml
    - include: tasks/ohmyzsh.yml
    - include: tasks/disable_login_banner.yml
    - include: tasks/ssmtp.yml
    - include: tasks/sshd_config.yml
    - include: tasks/ipfw.yml
    - include: tasks/fail2ban.yml

- hosts: hoth.tech-ninja.de
  tasks:
    - include: tasks/temp.yml